// Create a new user 
POST  http://localhost:5000/users
Content-Type: application/json

{
    "name": "sihur",
    "email": "sihur@gmail.com",
    "password": "12345",
    "confPassword": "12345",
    "role": "user"
}


### Get all users
GET http://localhost:5000/users

### Get user by id (ambil dari uuidnya)
GET http://localhost:5000/users/d2b17390-94c2-47e6-ac58-01f2caf53477


### Update user by id (ambil dari uuidnya)
PATCH http://localhost:5000/users/d2b17390-94c2-47e6-ac58-01f2caf53477
Content-Type: application/json

{
    "name": "Lanangejagatupdated",
    "email": "lj@gmail.com",
    "password": "",
    "confPassword": "",
    "role": "user"
}

### Delete user by id (ambil dari uuidnya)
DELETE http://localhost:5000/users/6cec456a-c541-43a4-8d06-bb50297ea86c

###
//Login sebagai admin
POST  http://localhost:5000/login
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "12345"
}

###
//login sebagai user
POST  http://localhost:5000/login
Content-Type: application/json

{
    "email": "sihur@gmail.com",
    "password": "12345"
}

###Get logged in user
GET http://localhost:5000/me

###Logout
DELETE http://localhost:5000/logout


###
// Get all products
GET http://localhost:5000/products

###
// Get products by id (ambil dari uuidnya)
GET http://localhost:5000/products/30320755-40af-4474-8e17-933643cf83b9

###
//Create Product 
POST http://localhost:5000/products
Content-Type: application/json

{
    "name": "Hodie Zipper",
    "price": 120000
}

###
//Update Product by id (ambil dari uuidnya)
PATCH http://localhost:5000/products/935c8fe0-dc1a-496c-b143-3ecb0acb8442
Content-Type: application/json

{
    "name": "Baju Koko",
    "price": 150000
}


###
//Delete Product by id (ambil dari uuidnya)
DELETE http://localhost:5000/products/a8fe2b36-c4a2-48b5-b766-f13fd9df78ec


